name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env: 
  AWS_REGION : "us-east-1"

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
      pull-requests: write   # Required for merging pull requests

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_IAM_ARN }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3


    - name: Terraform Init
      working-directory: src/terraform
      run: terraform init
    
    - name: Terraform Format
      working-directory: src/terraform
      run: terraform fmt -recursive

    - name: Terraform Validate
      working-directory: src/terraform
      run: terraform validate

    - name: Terraform Plan
      working-directory: src/terraform
      run: terraform plan

    - name: Terraform Apply
      working-directory: src/terraform
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve

  python-style-check:
    # Add pre-commit hooks, use this as failsafe
    name: Check Python Style
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Flake8
      run: pip install flake8

    - name: Run Flake8
      run: flake8 src/terraform/modules/lambda #Other folder paths can be added as needed, space delimited

  # python-tests:
  #   name: Run Python Tests
  #   runs-on: ubuntu-latest
  #   needs: terraform

  #   steps:
  #   - name: Checkout Code
  #     uses: actions/checkout@v3

    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.11'

    # - name: Install Dependencies
    #   run: pip install pytest

    # - name: Run Pytest
    #   run: pytest proj/src/pytests/tests

  auto-merge:
    name: Auto Merge dev to main on passing tests
    runs-on: ubuntu-latest
    needs: [terraform, python-style-check]
    if: github.ref == 'refs/heads/dev' && success()
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Git
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: Merge dev to main
      run: |
        git checkout main
        git merge dev
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}